name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated from v2 to v4

      - name: Setup Node
        uses: actions/setup-node@v4  # Updated from v1 to v4
        with:
          node-version: 20  # Updated from 16 to 20 (LTS)
          cache: 'npm'  # Added caching for faster installs

      - name: Install dependencies
        run: npm ci  # Replaced bahmutov/npm-install with standard npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Updated from v2 to v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated from v2 to v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # This is still current
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist